import 'package:pinkerest/models/category.dart';
import 'package:pinkerest/models/product.dart';

//import '../category.dart';
//import '../product.dart';

const CATEGORIES = const [
  category(id: "c1", name: "Accessories", image: "images/accessories/13.jpg"),
  category(id: "c2", name: "Bags", image: "images/bags/2.jpg"),
  category(id: "c3", name: "Candles", image: "images/candles/9.jpg"),
  category(id: "c4", name: "Watches", image: "images/clocks/22.jpg"),
  category(id: "c5", name: "Covers", image: "images/covers/23.jpg"),
  category(id: "c6", name: "Flowers", image: "images/flowers/1.jpg"),
  category(id: "c7", name: "Heels", image: "images/heels/21.jpg"),
  category(id: "c8", name: "Mugs", image: "images/mugs/20.jpg"),
  category(id: "c9", name: "Perfums", image: "images/perfums/22.jpg"),
  category(id: "c10", name: "toys", image: "images/toys/11.jpg"),
];
const DUMMY_PRODUCT = const [
  product(
      id: "m1",
      title: "Golden Diamond",
      imageUrl: "images/accessories/1.jpg",
      salary: "200\$",
      deliveryTime: "3-5 days",
      description:
          "A golden ring studded with diamonds makes your hand look attractive and elegant",
      categoryNumber: 'c1',
      rate: ""),
  product(
      id: "m2",
      title: "unique",
      imageUrl: "images/accessories/2.jpg",
      salary: "140\$",
      deliveryTime: "3-5 days",
      description:
          "A ring from ancient times, which is an antiquity of high value. Make sure to own it",
      rate: " ",
      categoryNumber: "c1"),
  product(
      id: "m3",
      title: "Blooded!",
      rate: " ",
      imageUrl: "images/accessories/3.jpg",
      salary: "60\$",
      deliveryTime: "3-5 days",
      description:
          "A very attractive ring with an eye-catching blood color. It is very cheerful. Make sure to buy it as well",
      categoryNumber: "c1"),
  product(
      id: "m4",
      title: "Golden Pink",
      rate: " ",
      imageUrl: "images/accessories/4.jpg",
      salary: "150\$",
      deliveryTime: "3-5 days",
      description:
          "The chain is a combination of gold and pink. It is a unique piece that will not be repeated!",
      categoryNumber: "c1"),

  product(
      id: "m5",
      rate: " ",
      title: "jasmine flower",
      imageUrl: "images/accessories/5.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "Complete accessories set with jasmine flower! It is a very distinctive and harmonious set! This is the harmony that is required to have",
      categoryNumber: "c1"),

  product(
      id: "m6",
      title: "cute One",
      rate: " ",
      imageUrl: "images/accessories/6.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A very thin chain that suits you, my lady, with great beauty and elegance, with its calm, attractive color",
      categoryNumber: "c1"),

  product(
      id: "m7",
      title: "cherry ",
      rate: " ",
      imageUrl: "images/accessories/7.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description:
          "A very attractive summer chain with a delicious cherry shape! It is a beautiful and fashionable piece, do not miss it!",
      categoryNumber: "c1"),

  product(
      id: "m8",
      title: "red heart",
      rate: " ",
      imageUrl: "images/accessories/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "The red heart is a symbol of love and beauty! A piece that will not be repeated, buy it quickly",
      categoryNumber: "c1"),

  product(
      id: "m9",
      title: "elegant ",
      rate: " ",
      imageUrl: "images/accessories/9.jpg",
      salary: "110\$",
      deliveryTime: "3-5 days",
      description:
          "A quiet and elegant piece that cannot be described in words",
      categoryNumber: "c1"),

  product(
      id: "m10",
      title: "pieces of art ",
      rate: " ",
      imageUrl: "images/accessories/10.jpg",
      salary: "120\$",
      deliveryTime: "3-5 days",
      description:
          "I can't believe these three pieces of art are a wonderful collection in different and distinctive shapes",
      categoryNumber: "c1"),

  product(
    id: "m11",
    title: " solar system",
    imageUrl: "images/accessories/11.jpg",
    salary: "100\$",
    deliveryTime: "3-5 days",
    description:
        "The beauty of these pieces is like the beauty of the solar system. Oh my God, they are truly beautiful like the moon on a dark night!",
    categoryNumber: "c1",
    rate: " ",
  ),

  product(
      id: "m12",
      title: "white gemstone ",
      rate: " ",
      imageUrl: "images/accessories/12.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A chain with a white gemstone. It is specially designed for those with sophisticated taste, and it is certainly you, ma’am.",
      categoryNumber: "c1"),

  product(
      id: "m13",
      title: "B&W combination",
      rate: " ",
      imageUrl: "images/accessories/13.jpg",
      salary: "80\$",
      deliveryTime: "3-5 days",
      description:
          "Black and white combination? Who said that white is the same as black? Combining the two colors together in one group led to the appearance of this elegant magic",
      categoryNumber: "c1"),

  product(
      id: "m14",
      title: " ",
      imageUrl: "images/accessories/14.jpg",
      salary: "100\$",
      deliveryTime: "3-5 days",
      rate: " ",
      description:
          "Wonderful lavender accessory! This color is the fashion of this era! Don't miss it",
      categoryNumber: "c1"),
  //product(id: "m15", title: " ", imageUrl: "images/accessories/15.jpg", salary: "70\$", rate: " ", deliveryTime: "3-5 days", description: "", categoryNumber: "c1"),
  //product(id: "m16", title: " ", imageUrl: "images/accessories/16.jpg", salary: "130\$",rate: " ",  deliveryTime: "3-5 days",description: "", categoryNumber: "c1"),
  //product(id: "m17",rate: " ", title: " ", imageUrl: "images/accessories/17.jpg", salary: "60\$",  deliveryTime :"3-5 days", description: "", categoryNumber: "c1"),
  //product(id: "m18",rate: " ", title: " ", imageUrl: "images/accessories/18.jpg", salary: "150\$",  deliveryTime: "3-5 days", description: "", categoryNumber: "c1"),
  product(
      id: "m1",
      rate: " ",
      title: " camel-colored",
      imageUrl: "images/bags/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A camel-colored bag! It suits people with a childish spirit who still cling to their innocent personalities!",
      categoryNumber: "c2"),

  product(
      id: "m2",
      rate: " ",
      title: "White Heart",
      imageUrl: "images/bags/2.jpg",
      salary: "150\$",
      deliveryTime: "3-5 days",
      description:
          "A pure white heart-shaped bag that looks exactly like your heart and is specially designed for those with pure hearts who love goodness and beauty!",
      categoryNumber: "c2"),

  product(
      id: "m3",
      rate: " ",
      title: "spring bag",
      imageUrl: "images/bags/3.jpg",
      salary: "180\$",
      deliveryTime: "3-5 days",
      description:
          "An embroidered bag in a mint color that resembles spring in its beauty, giving your look liveliness as if we are inside a picturesque garden.",
      categoryNumber: "c2"),

  product(
      id: "m4",
      rate: " ",
      title: "life-loving bag ",
      imageUrl: "images/bags/4.jpg",
      salary: "190\$",
      deliveryTime: "3-5 days",
      description:
          "A heart-shaped bag that resembles your life-loving and fun-loving heart! Buy it now to give you a feeling of love, comfort and beauty",
      categoryNumber: "c2"),

  product(
      id: "m5",
      rate: "calm pink bag",
      title: "pink peice",
      imageUrl: "images/bags/5.jpg",
      salary: "200\$",
      deliveryTime: "3-5 days",
      description:
          "A bag in an elegant and calm pink color that suits every calm and sophisticated woman! Don't miss it",
      categoryNumber: "c2"),

  product(
      id: "m6",
      rate: " ",
      title: "sea & sky bag",
      imageUrl: "images/bags/6.jpg",
      salary: "230\$",
      deliveryTime: "3-5 days",
      description:
          "A bag that combines sea and sky! Its color is yellow, which resembles a stationary sun, and blue, which resembles sea waves! It's really amazing!",
      categoryNumber: "c2"),

  product(
      id: "m7",
      rate: " ",
      title: "calm colored",
      imageUrl: "images/bags/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A bag of many colors, like a painting in a museum! Very suitable for people with calm taste who love somewhat calm fashion!",
      categoryNumber: "c2"),

  product(
      id: "m8",
      rate: " ",
      title: "green spring bag",
      imageUrl: "images/bags/8.jpg",
      salary: "150\$",
      deliveryTime: "3-5 days",
      description:
          "A green bag that resembles the beauty of plants in the green spring! It really has a cheerful nature that suits women who love bright and eye-catching things! Don't miss it",
      categoryNumber: "c2"),
  product(
      id: "m9",
      rate: " ",
      title: "soft yellow bag",
      imageUrl: "images/bags/9.jpg",
      salary: "170\$",
      deliveryTime: "3-5 days",
      description:
          "A soft yellow bag with a calm and attractive decoration that is truly unique!",
      categoryNumber: "c2"),
  product(
      id: "m10",
      rate: "",
      title: "yellow white beads ",
      imageUrl: "images/bags/10.jpg",
      salary: "220\$",
      deliveryTime: "3-5 days",
      description:
          "A bag with a mixture of yellow and embroidered with white beads, giving it a truly stunning appearance! It is a rare piece designed specifically for lovers of beauty and tranquility!",
      categoryNumber: "c2"),
  product(
      id: "m11",
      rate: " ",
      title: "pink white beads",
      imageUrl: "images/bags/11.jpg",
      salary: "270\$",
      deliveryTime: "3-5 days",
      description:
          "A bag with a mix of pink and embroidered with white beads, giving it a truly stunning look! It is a rare piece designed specifically for lovers of beauty and tranquility!",
      categoryNumber: "c2"),
  product(
      id: "m12",
      rate: " ",
      title: "coffee colored bag",
      imageUrl: "images/bags/12.jpg",
      salary: "300\$",
      deliveryTime: "3-5 days",
      description:
          "A brown bag, which is in fashion this year and every year! It's a warm color, like a cup of tea in the middle of a good atmosphere! Never miss this piece!",
      categoryNumber: "c2"),
  /*product(
      id: "m13",
      rate: " ",
      title: " ",
      imageUrl: "images/bags/13.jpg",
      salary: "180\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c2"),*/
  product(
      id: "m14",
      rate: " ",
      title: "scarf bag",
      imageUrl: "images/bags/14.jpg",
      salary: "400\$",
      deliveryTime: "3-5 days",
      description:
          "A very soft pink bag with a scarf that resembles the beauty of veiled women! It is a unique piece in 70s fashion for lovers of valuable items!",
      categoryNumber: "c2"),
  product(
      id: "m15",
      rate: " ",
      title: "white & gold",
      imageUrl: "images/bags/15.jpg",
      salary: "250\$",
      deliveryTime: "3-5 days",
      description:
          "Nothing beats the beauty of white, especially if mixed with gold! What a beauty and her bag was truly gold!",
      categoryNumber: "c2"),
  product(
      id: "m16",
      rate: " ",
      title: "calm green",
      imageUrl: "images/bags/16.jpg",
      salary: "290\$",
      deliveryTime: "3-5 days",
      description:
          "Nothing beats the beauty of calm green, especially if mixed with gold! What a beauty and her bag was truly gold!",
      categoryNumber: "c2"),
  product(
      id: "m17",
      rate: " ",
      title: "lavender-colored bag",
      imageUrl: "images/bags/17.jpg",
      salary: "450\$",
      deliveryTime: "3-5 days",
      description:
          "A fragrant lavender-colored bag that looks as if she is escaping from the garden!",
      categoryNumber: "c2"),
  product(
      id: "m18",
      rate: " ",
      title: "colorful bags",
      imageUrl: "images/bags/18.jpg",
      salary: "500\$",
      deliveryTime: "3-5 days",
      description:
          "A collection with attractive design and colors! Choose your favorite design in your favorite color from this range of colors!",
      categoryNumber: "c2"),

  //================================
  product(
      id: "m1",
      rate: " ",
      title: "marble candles",
      imageUrl: "images/candles/1.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A set of candles in the shape of precious marble, and it is a set extracted from nature for nature lovers!",
      categoryNumber: "c3"),
  product(
      id: "m2",
      rate: " ",
      title: "colorgul candles",
      imageUrl: "images/candles/2.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of relaxing candles in different colors! Get your favorite color",
      categoryNumber: "c3"),

  product(
      id: "m3",
      rate: " ",
      title: "tulip candles",
      imageUrl: "images/candles/3.jpg",
      salary: "150\$",
      deliveryTime: "3-5 days",
      description:
          "A candles with a natural shape and smell, as it is extracted from the fragrant tulip flower, which has a beautiful shape and color",
      categoryNumber: "c3"),
  product(
      id: "m4",
      rate: " ",
      title: "butterfly candles",
      imageUrl: "images/candles/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of butterfly-shaped candles that makes you feel the lightness and beauty of the butterfly",
      categoryNumber: "c"),
  product(
      id: "m5",
      rate: " ",
      title: "butterfly collection",
      imageUrl: "images/candles/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A distinctive collection of candles in a very distinctive butterfly shape, as if it were flying in the middle of spring fields",
      categoryNumber: "c3"),
  product(
      id: "m6",
      rate: " ",
      title: "doll candles",
      imageUrl: "images/candles/6.jpg",
      salary: "140\$",
      deliveryTime: "3-5 days",
      description:
          "Cute doll-shaped candles that suit your innocent, childish personality! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m7",
      rate: " ",
      title: "cloud candles",
      imageUrl: "images/candles/7.jpg",
      salary: "120\$",
      deliveryTime: "3-5 days",
      description:
          "Cute cloud-shaped candles that suit your innocent, childish personality! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m8",
      rate: " ",
      title: "rose candles",
      imageUrl: "images/candles/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Cute rose-shaped candles in autumn colors that suit your calm personality! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m9",
      rate: " ",
      title: "rose autumn candles",
      imageUrl: "images/candles/9.jpg",
      salary: "100\$",
      deliveryTime: "3-5 days",
      description:
          "Cute rose-shaped candles in autumn colors that suit your calm personality! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m10",
      rate: " ",
      title: "molten waves",
      imageUrl: "images/candles/10.jpg",
      salary: "80\$",
      deliveryTime: "3-5 days",
      description:
          "Candles shaped like molten waves that resemble ice! Don't miss it!",
      categoryNumber: "c3"),
  /*product(
      id: "m11",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/11.jpg",
      salary: "110\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),*/
  product(
      id: "m12",
      rate: " ",
      title: "melted heart",
      imageUrl: "images/candles/12.jpg",
      salary: "75\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the shape of a heart that melts with love for all that is beautiful! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m13",
      rate: " ",
      title: "Beauty candle",
      imageUrl: "images/candles/13.jpg",
      salary: "120\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the form of a mold as beautiful as yours, ma'am! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m14",
      rate: " ",
      title: "pink&lavender",
      imageUrl: "images/candles/14.jpg",
      salary: "80\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the form of a beauty bar with a mixture of pink blossom and lavender, just like your beauty, ma'am! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m15",
      rate: " ",
      title: "shell Candles",
      imageUrl: "images/candles/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the shape of a mold of beauty resembling sea waves and shells, just like your beauty, ma’am! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m16",
      rate: " ",
      title: "clear clouds",
      imageUrl: "images/candles/16.jpg",
      salary: "100\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the shape of a beauty mold that resembles clear clouds in the sky, just like your beauty, ma’am! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m17",
      rate: " ",
      title: "molten flowers",
      imageUrl: "images/candles/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the form of a beauty mold that resembles molten flowers in the heat, like your beauty, my lady! Don't miss it!",
      categoryNumber: "c3"),
  /*product(
      id: "m18",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/18.jpg",
      salary: "85\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),*/
  product(
      id: "m19",
      rate: " ",
      title: "Red Sea shells",
      imageUrl: "images/candles/19.jpg",
      salary: "70\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the shape of a beauty bar that resembles the shells of the Red Sea that swim in the waves, like your beauty, my lady! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m20",
      rate: " ",
      title: "three-dimensional",
      imageUrl: "images/candles/20.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the form of a beautiful mold that resembles three-dimensional circles! Don't miss it!",
      categoryNumber: "c3"),
  product(
      id: "m21",
      rate: " ",
      title: "simple beauty",
      imageUrl: "images/candles/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the form of a bar of simple beauty like the simplicity of your heart, do not miss it!",
      categoryNumber: "c3"),
  /* product(
      id: "m22",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/22.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),*/
  product(
      id: "m23",
      rate: " ",
      title: "random beauty",
      imageUrl: "images/candles/23.jpg",
      salary: "55\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the form of a bar of simple, random beauty like the simplicity of your heart, do not miss it!",
      categoryNumber: "c3"),
  product(
      id: "m24",
      rate: " ",
      title: "decorated beads",
      imageUrl: "images/candles/24.jpg",
      salary: "60\$",
      deliveryTime: "3-5 days",
      description:
          "Bar-shaped candles of simple, random beauty with decorated beads scattered like the simplicity of your heart. Don't miss them!",
      categoryNumber: "c3"),
  /*product(
      id: "m25",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/25.jpg",
      salary: "80\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),*/
  /*product(
      id: "m26",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/26.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),*/
  product(
      id: "m27",
      rate: " ",
      title: " fresh fruits",
      imageUrl: "images/candles/27.jpg",
      salary: "110\$",
      deliveryTime: "3-5 days",
      description:
          "Candles in the shape of fresh summer fruits, don't miss them!",
      categoryNumber: "c3"),
  /*product(
      id: "m28",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/28.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),
  product(
      id: "m29",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/29.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),
  product(
      id: "m30",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/30.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),
  product(
      id: "m31",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/31.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),
  product(
      id: "m32",
      rate: " ",
      title: " ",
      imageUrl: "images/candles/32.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "",
      categoryNumber: "c3"),*/
  product(
      id: "m1",
      rate: " ",
      title: "flower watch",
      imageUrl: "images/clocks/1.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m2",
      rate: " ",
      title: "tulip watch",
      imageUrl: "images/clocks/2.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m3",
      rate: " ",
      title: "mint watch",
      imageUrl: "images/clocks/3.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  /*product(
      id: "m4",
      rate: " ",
      title: "modern watch",
      imageUrl: "images/clocks/.4jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),*/
  product(
      id: "m5",
      rate: " ",
      title: "black watch",
      imageUrl: "images/clocks/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m6",
      rate: " ",
      title: "classic watch",
      imageUrl: "images/clocks/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m7",
      rate: " ",
      title: "royal watch",
      imageUrl: "images/clocks/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m8",
      rate: " ",
      title: "butterfly watch",
      imageUrl: "images/clocks/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m9",
      rate: " ",
      title: "golden watch",
      imageUrl: "images/clocks/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m10",
      rate: " ",
      title: "Blooded watch",
      imageUrl: "images/clocks/10.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m11",
      rate: " ",
      title: "pink watch",
      imageUrl: "images/clocks/11.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m12",
      rate: " ",
      title: "soft-Gold watch",
      imageUrl: "images/clocks/12.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m13",
      rate: " ",
      title: "Lavender watch",
      imageUrl: "images/clocks/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m14",
      rate: " ",
      title: "spring-Gold watch",
      imageUrl: "images/clocks/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m15",
      rate: " ",
      title: "Beige watch",
      imageUrl: "images/clocks/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m16",
      rate: " ",
      title: "soft collection",
      imageUrl: "images/clocks/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m17",
      rate: " ",
      title: "Baby pink watch",
      imageUrl: "images/clocks/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m18",
      rate: " ",
      title: "Rose Watch",
      imageUrl: "images/clocks/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m19",
      rate: " ",
      title: "soft-Blue watch",
      imageUrl: "images/clocks/19.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m20",
      rate: " ",
      title: "Dark Blue watch",
      imageUrl: "images/clocks/20.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m21",
      rate: " ",
      title: "Dark Beige watch",
      imageUrl: "images/clocks/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m22",
      rate: " ",
      title: "soft watch",
      imageUrl: "images/clocks/22.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),
  product(
      id: "m23",
      rate: " ",
      title: "Automn collection",
      imageUrl: "images/clocks/23.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A beautiful watch with a simple, modern design, specially designed for lovers of beauty and simplicity! Don't miss the chance to get it",
      categoryNumber: "c4"),

  product(
      id: "m1",
      rate: " ",
      title: "Aurura cover",
      imageUrl: "images/covers/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m2",
      rate: " ",
      title: "blue cover",
      imageUrl: "images/covers/2.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m3",
      rate: " ",
      title: "baby-blue cover ",
      imageUrl: "images/covers/3.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m4",
      rate: " ",
      title: "Lavender cover",
      imageUrl: "images/covers/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m5",
      rate: " ",
      title: "mixed cover",
      imageUrl: "images/covers/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m6",
      rate: " ",
      title: "garden cover",
      imageUrl: "images/covers/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m7",
      rate: " ",
      title: "mint cover",
      imageUrl: "images/covers/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m8",
      rate: " ",
      title: "flower cover",
      imageUrl: "images/covers/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m9",
      rate: " ",
      title: "heart cover",
      imageUrl: "images/covers/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m10",
      rate: " ",
      title: "jasmine cover",
      imageUrl: "images/covers/10.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m11",
      rate: " ",
      title: "Girls cover",
      imageUrl: "images/covers/11.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m12",
      rate: " ",
      title: "blood cover",
      imageUrl: "images/covers/12.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m13",
      rate: " ",
      title: "heart cover",
      imageUrl: "images/covers/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m14",
      rate: " ",
      title: "butterfly cover",
      imageUrl: "images/covers/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m15",
      rate: " ",
      title: "cartoon cover",
      imageUrl: "images/covers/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m16",
      rate: " ",
      title: "heart cover",
      imageUrl: "images/covers/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m17",
      rate: " ",
      title: "wish cover",
      imageUrl: "images/covers/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m18",
      rate: " ",
      title: "silver cover",
      imageUrl: "images/covers/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m19",
      rate: " ",
      title: "butterfly",
      imageUrl: "images/covers/19.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m20",
      rate: " ",
      title: "blue cover",
      imageUrl: "images/covers/20.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m21",
      rate: " ",
      title: "pink cover",
      imageUrl: "images/covers/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "make your phone elegant!",
      categoryNumber: "c5"),
  product(
      id: "m1",
      rate: " ",
      title: "Lavender flower",
      imageUrl: "images/flowers/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m2",
      rate: " ",
      title: "soft lavender flower",
      imageUrl: "images/flowers/2.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m3",
      rate: " ",
      title: "mini-red flower",
      imageUrl: "images/flowers/3.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m4",
      rate: " ",
      title: "cheers-colored flower",
      imageUrl: "images/flowers/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m5",
      rate: " ",
      title: "pink beans flower",
      imageUrl: "images/flowers/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m6",
      rate: " ",
      title: "Dark red flower",
      imageUrl: "images/flowers/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m7",
      rate: " ",
      title: "cute pink flower",
      imageUrl: "images/flowers/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m8",
      rate: " ",
      title: "pinl-Lavender flower",
      imageUrl: "images/flowers/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m9",
      rate: " ",
      title: "Rose collection",
      imageUrl: "images/flowers/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m10",
      rate: " ",
      title: "spring's pink flower",
      imageUrl: "images/flowers/10.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m11",
      rate: " ",
      title: "Yellow flower",
      imageUrl: "images/flowers/11.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m12",
      rate: " ",
      title: "Black-rosed flower",
      imageUrl: "images/flowers/12.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m13",
      rate: " ",
      title: "Green-rosed flower",
      imageUrl: "images/flowers/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m14",
      rate: " ",
      title: "soft-Rose flower",
      imageUrl: "images/flowers/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m15",
      rate: " ",
      title: "Jasmine flower",
      imageUrl: "images/flowers/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m16",
      rate: " ",
      title: "Blooded flower",
      imageUrl: "images/flowers/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  /*product(
      id: "m17",
      rate: " ",
      title: "",
      imageUrl: "images/flowers/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),*/
  product(
      id: "m18",
      rate: " ",
      title: "Opened-pink flower",
      imageUrl: "images/flowers/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m19",
      rate: " ",
      title: "sun flower",
      imageUrl: "images/flowers/19.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m20",
      rate: " ",
      title: "pink-sun flower",
      imageUrl: "images/flowers/20.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m21",
      rate: " ",
      title: "minted flower",
      imageUrl: "images/flowers/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m22",
      rate: " ",
      title: "Tulip flower",
      imageUrl: "images/flowers/22.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m23",
      rate: " ",
      title: "sun-Rose flower",
      imageUrl: "images/flowers/23.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m24",
      rate: " ",
      title: "White flower",
      imageUrl: "images/flowers/24.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m25",
      rate: " ",
      title: "B & W flower",
      imageUrl: "images/flowers/25.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A collection of flowers with distinctive shapes and wonderful scents. It is suitable as a gift for all occasions and at all times.",
      categoryNumber: "c6"),
  product(
      id: "m1",
      rate: " ",
      title: "purple Heels",
      imageUrl: "images/heels/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m2",
      rate: " ",
      title: "Silver heels",
      imageUrl: "images/heels/2.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m3",
      rate: " ",
      title: "Yellow heels",
      imageUrl: "images/heels/3.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m4",
      rate: " ",
      title: "pink Heels",
      imageUrl: "images/heels/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  /*product(
      id: "m5",
      rate: " ",
      title: "Elegant Leather High Heels for Women ",
      imageUrl: "images/heels/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),*/
  product(
      id: "m6",
      rate: " ",
      title: "Butterfly heels",
      imageUrl: "images/heels/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m7",
      rate: " ",
      title: "transparent heels",
      imageUrl: "images/heels/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m8",
      rate: " ",
      title: "pink slippers",
      imageUrl: "images/heels/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m9",
      rate: " ",
      title: "black slippers",
      imageUrl: "images/heels/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m10",
      rate: " ",
      title: "sun-flower slipper",
      imageUrl: "images/heels/10.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m11",
      rate: " ",
      title: "beige heels",
      imageUrl: "images/heels/11.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m12",
      rate: " ",
      title: "glitter heels",
      imageUrl: "images/heels/12.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m13",
      rate: " ",
      title: "blue heels",
      imageUrl: "images/heels/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m14",
      rate: " ",
      title: "red heels",
      imageUrl: "images/heels/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m15",
      rate: " ",
      title: "pink slipper",
      imageUrl: "images/heels/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m16",
      rate: " ",
      title: "green heels",
      imageUrl: "images/heels/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m17",
      rate: " ",
      title: "mint slipper",
      imageUrl: "images/heels/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m18",
      rate: " ",
      title: "mint slipper2",
      imageUrl: "images/heels/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m19",
      rate: " ",
      title: "rose heels",
      imageUrl: "images/heels/19.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m20",
      rate: " ",
      title: "soft rose heels",
      imageUrl: "images/heels/20.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m21",
      rate: " ",
      title: "golden heels",
      imageUrl: "images/heels/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Women's high heel shoes made of genuine leather for daily use",
      categoryNumber: "c7"),
  product(
      id: "m1",
      rate: " ",
      title: "colorful Mug",
      imageUrl: "images/mugs/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m2",
      rate: " ",
      title: "yellow mug",
      imageUrl: "images/mugs/2.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m3",
      rate: " ",
      title: "butterfly mug",
      imageUrl: "images/mugs/3.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  /*product(
      id: "m4",
      rate: " ",
      title: "Mugs Collection ",
      imageUrl: "images/mugs/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),*/
  product(
      id: "m5",
      rate: " ",
      title: "Hello-Kitty mug",
      imageUrl: "images/mugs/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m6",
      rate: " ",
      title: "Rabbit mug",
      imageUrl: "images/mugs/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m7",
      rate: " ",
      title: "cute mug",
      imageUrl: "images/mugs/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m8",
      rate: " ",
      title: "flower mug",
      imageUrl: "images/mugs/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m9",
      rate: " ",
      title: "Aurura mug",
      imageUrl: "images/mugs/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m10",
      rate: " ",
      title: "pink mug",
      imageUrl: "images/mugs/10.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m11",
      rate: " ",
      title: "tulip mug",
      imageUrl: "images/mugs/11.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m12",
      rate: " ",
      title: "butterfly mug",
      imageUrl: "images/mugs/12.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m13",
      rate: " ",
      title: "rabbit mug",
      imageUrl: "images/mugs/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m14",
      rate: " ",
      title: "sponge-pop mug",
      imageUrl: "images/mugs/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m15",
      rate: " ",
      title: "white mug",
      imageUrl: "images/mugs/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m16",
      rate: " ",
      title: "happy mug",
      imageUrl: "images/mugs/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m17",
      rate: " ",
      title: "Tanna mug",
      imageUrl: "images/mugs/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m18",
      rate: " ",
      title: "cat mug",
      imageUrl: "images/mugs/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m19",
      rate: " ",
      title: "Mugs Collection ",
      imageUrl: "images/mugs/19.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m20",
      rate: " ",
      title: "Mugs Collection ",
      imageUrl: "images/mugs/20.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m21",
      rate: " ",
      title: "Mugs Collection ",
      imageUrl: "images/mugs/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Distinctive and elegant mugs with high-quality, durable and environmentally friendly materials. Choose from different designs and colors that suit your style. Perfect as a gift or to add luxury to your daily coffee or tea routine.",
      categoryNumber: "c8"),
  product(
      id: "m1",
      rate: "",
      title: "VERSACE perfume",
      imageUrl: "images/perfums/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m2",
      rate: " ",
      title: "Si perfume ",
      imageUrl: "images/perfums/2.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m3",
      rate: " ",
      title: "perfume ",
      imageUrl: "images/perfums/3.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m4",
      rate: " ",
      title: "KAY perfume ",
      imageUrl: "images/perfums/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m5",
      rate: " ",
      title: "KAY perfume  ",
      imageUrl: "images/perfums/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m6",
      rate: " ",
      title: "PRADA perfume",
      imageUrl: "images/perfums/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m7",
      rate: " ",
      title: "VERSACE perfume",
      imageUrl: "images/perfums/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m8",
      rate: " ",
      title: "VERSACE perfume",
      imageUrl: "images/perfums/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m9",
      rate: " ",
      title: "Jadore perfume",
      imageUrl: "images/perfums/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m10",
      rate: " ",
      title: "perfume ",
      imageUrl: "images/perfums/10.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m11",
      rate: " ",
      title: "perfume",
      imageUrl: "images/perfums/11.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m12",
      rate: " ",
      title: "farmasi perfume ",
      imageUrl: "images/perfums/12.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m13",
      rate: " ",
      title: "L'INTERDIT perfume",
      imageUrl: "images/perfums/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m14",
      rate: " ",
      title: "VALENTINO perfume ",
      imageUrl: "images/perfums/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m15",
      rate: " ",
      title: "PRADA perfume",
      imageUrl: "images/perfums/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m16",
      rate: " ",
      title: "VERSACE perfume ",
      imageUrl: "images/perfums/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m17",
      rate: " ",
      title: "CHANEL perfume",
      imageUrl: "images/perfums/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m18",
      rate: " ",
      title: "COCO CHANEL perfume",
      imageUrl: "images/perfums/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m19",
      rate: " ",
      title: "Miss Dior perfume",
      imageUrl: "images/perfums/19.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m20",
      rate: " ",
      title: "Miniso perfume",
      imageUrl: "images/perfums/20.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m21",
      rate: " ",
      title: "perfume",
      imageUrl: "images/perfums/21.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m22",
      rate: " ",
      title: "DAISY perfum",
      imageUrl: "images/perfums/22.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A luxurious perfum characterized by its unique and distinctive scent that combines elegance and femininity/masculinity. The perfume comes in an elegant and attractive bottle that reflects the beauty and quality of the product. It is characterized by its high stability on the skin, which makes it an ideal choice for all occasions.",
      categoryNumber: "c9"),
  product(
      id: "m1",
      rate: " ",
      title: "Pink plush teddy bear toy",
      imageUrl: "images/toys/1.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "Pink plush teddy bear toy",
      categoryNumber: "c10"),
  product(
      id: "m2",
      rate: " ",
      title: "Bear Plush Toy",
      imageUrl: "images/toys/2.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "The plush toy bear has different distinctive colors and wears wonderful clothes that children will love very much",
      categoryNumber: "c10"),
  product(
      id: "m3",
      rate: " ",
      title: "Purple teddy bear plush toy ",
      imageUrl: "images/toys/3.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "Adorable purple teddy bear plush toy",
      categoryNumber: "c10"),
  product(
      id: "m4",
      rate: " ",
      title: "Bear Plush Toy ",
      imageUrl: "images/toys/4.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "Plush bear toy in different distinctive colors",
      categoryNumber: "c10"),
  product(
      id: "m5",
      rate: " ",
      title: "Green bear plush toy ",
      imageUrl: "images/toys/5.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "Green plush bear toy at a special price",
      categoryNumber: "10"),
  product(
      id: "m6",
      rate: " ",
      title: "Bear Plush Toy",
      imageUrl: "images/toys/6.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "Plush bear toy in different distinctive colors",
      categoryNumber: "c10"),
  product(
      id: "m7",
      rate: " ",
      title: "Yellow bear",
      imageUrl: "images/toys/7.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A yellow bear with a white belly with a sun on it and wearing a birthday hat",
      categoryNumber: "c10"),
  product(
      id: "m8",
      rate: " ",
      title: "Yellow bear ",
      imageUrl: "images/toys/8.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "A yellow bear with a white belly with a sun on it",
      categoryNumber: "c10"),
  product(
      id: "m9",
      rate: " ",
      title: "Pink bear ",
      imageUrl: "images/toys/9.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "A pink teddy bear with a white belly and a multicolored rainbow pattern",
      categoryNumber: "c10"),
  product(
      id: "m10",
      rate: " ",
      title: "A white bear",
      imageUrl: "images/toys/10.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description: "Big white teddy bear with a little bit of pink inside",
      categoryNumber: "c10"),
  product(
      id: "m11",
      rate: " ",
      title: "White Bear Plush Toy",
      imageUrl: "images/toys/11.jpg",
      salary: "90\$",
      deliveryTime: "3-5 days",
      description: "cute toy for children",
      categoryNumber: "c10"),
  product(
      id: "m12",
      rate: " ",
      title: "Light brown bear",
      imageUrl: "images/toys/12.jpg",
      salary: "99\$",
      deliveryTime: "3-5 days",
      description: "A brown bear wearing a green costume that kids will love",
      categoryNumber: "c10"),
  product(
      id: "m13",
      rate: " ",
      title: "White Bear Plush Toy",
      imageUrl: "images/toys/13.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "A white bear wearing a pink uniform is a grizzly bear",
      categoryNumber: "c10"),
  product(
      id: "m14",
      rate: " ",
      title: "White Bear Plush Toy",
      imageUrl: "images/toys/14.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "White bear wearing a yellow outfit",
      categoryNumber: "c10"),
  product(
      id: "m15",
      rate: " ",
      title: "White Bear ",
      imageUrl: "images/toys/15.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "A white bear wearing a pink outfit holding an ice cream",
      categoryNumber: "c10"),
  product(
      id: "m16",
      rate: " ",
      title: "White Bear Plush Toy",
      imageUrl: "images/toys/16.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "cute toy for children",
      categoryNumber: "c10"),
  product(
      id: "m17",
      rate: " ",
      title: "Brown Bear Plush Toy",
      imageUrl: "images/toys/17.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description:
          "Cute giant brown teddy bear. Birthday & Christmas gift idea",
      categoryNumber: "c10"),
  product(
      id: "m18",
      rate: " ",
      title: "pink bear ",
      imageUrl: "images/toys/18.jpg",
      salary: "130\$",
      deliveryTime: "3-5 days",
      description: "A wonderful teddy bear as a gift. How about you buy it?",
      categoryNumber: "c10"),
];
